### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'accepted_renderer'

### ISSUE THREAD

**Issue by alfdev** [aschn/drf-tracking#38]
Seems there is the same problem like the #27 but now the missing attribute is 'accepted_renderer'.

I'm using:
drf-tracking (1.1.0)
django-rest-swagger (0.3.5)
Django (1.10.5)

Thanks

**Comment by alfdev** [comment]
I've downgraded the following packages and now works:

Django from 1.10.5 to 1.10.2
djangorestframework from 3.5.3 to 3.5.1
drf-tracking from 1.1.0 to 1.0.1

maybe this info can help you to solve the bug.

**Comment by avelis** [comment]
@alfdev Thats for the debugging info!

**Comment by lexapi** [comment]
We are use Django 1.10.5 and djangorestframework 3.4.6 without drf-tracking  - same problem

**Comment by CamelCaseNotation** [comment]
Could you post your settings.py file in your project directory please? I am having the same issue :(

**Comment by avelis** [comment]
Following my gut feeling to this, it would appear the Request object is not being converted to a DRF-Request object prior to accessing the `accepted_renderer` attribute. How and why is really the point of investigation.

Since, LoggingMixin is added per view I would look into the inheritance tree and start eliminating if it's a DRF + DRF-tracking issue or isolated to one library vs the other.

**Comment by i4s-acarrasco** [comment]
We are having the same problem without drf-tracking:
Django 1.10.4
djangorestframework 3.5.3
The problem occurs after updating djangorestframework from < 3 to 3.5.3 and Django from 1.6.5 to 1.10.4

**Comment by facconi** [comment]
I have solved removing (commenting) the CoreJSONRenderer from the settings.
I hope this helps!

**Comment by avelis** [comment]
@facconi Thanks for sharing your resolution. Would your solution work everyone or is it specific to your install settings?

**Comment by facconi** [comment]
The real solution was that I was using the CoreJSONRenderer without having coreapi in the requirements.txt file.
Installing coreapi fixed the problem!
I think it's a solution that should work for everybody.

**Comment by rnegron** [comment]
None of the fixes mentioned here applied to my scenario with this bug... In my case, the following line seems to be the problem: https://github.com/aschn/drf-tracking/blob/5acbd207c06897c9ba65bfe141c8c886eb6fc508/rest_framework_tracking/base_mixins.py#L29

Removing that line and letting the `super()` call take place correctly sets up the `accepted_renderer` property on the request (via a `perform_content_negotiation()` inside the `initial` of the `APIView` class). In the end, the same code is called at [line 41](https://github.com/aschn/drf-tracking/blob/5acbd207c06897c9ba65bfe141c8c886eb6fc508/rest_framework_tracking/base_mixins.py#L41) of that same function.

Is this a bug or am I missing something?

**Comment by RuslanButko** [comment]
```
from django.utils.timezone import now
from rest_framework_tracking.base_mixins import BaseLoggingMixin
from rest_framework_tracking.mixins import LoggingMixin

class CustomLoginMixin(LoggingMixin):

    def initial(self, request, *args, **kwargs):
        self.log = {}
        self.log['requested_at'] = now()
        self.log['data'] = self._clean_data(request.data)

        super(BaseLoggingMixin, self).initial(request, *args, **kwargs)

        try:
            # Accessing request.data *for the first time* parses the request body, which may raise
            # ParseError and UnsupportedMediaType exceptions. It's important not to swallow these,
            # as (depending on implementation details) they may only get raised this once, and
            # DRF logic needs them to be raised by the view for error handling to work correctly.
            data = self.request.data.dict()
        except AttributeError:
            data = self.request.data
        self.log['data'] = self._clean_data(data)
```

This solution works for me. The main idea replace 

> request.**body** with request.**data**

`self.log['data'] = self._clean_data(request.data)`
and run parent super 
`super(BaseLoggingMixin, self).initial(request, *args, **kwargs)`

**Comment by Kiel-Hyre** [comment]
hi im late to party, but I had this bug too.

My Code is just a simple inherit of LoggingMixin
No fancy overriding since I just want to use the default.

So I encounterd this bug,  when I tried to upload a gif with 4.6mb   ... has no attribute 'accepted_renderer.'

views.py
```
class CustomLogging(LoggingMixin, APIView):
        def post(self):
            # do something here
```
I tried to delete the LoggingMixin from the code. It works tho. But why would I do that  since I want the functionalities of the LoggingMixin.

And so I read the errors. and I encounter this.

During handling of the above exception (Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.), another exception occurred:

in which it pertains to the settings.py DATA_UPLOAD_MAX_MEMORY_SIZE = 2.5mb (default)

so everyone who encounter this change the size of the upload_max.

Though again i do not understand why its working smoothly without the LogginMixin, thanks for everyone who answer this one :)

**Comment by Kiel-Hyre** [comment]
hi, it seems im late to the party. 
Encountered this bug too. 
1. Scenario : Uploading 4.6mb gif
2. Exception Value: Request 'object' has no attribute 'accepted_renderer.'
3. Exception Location: .../python3.6/dist-packages/rest_framework/request.py in __getattr__, line 411

Code:

views.py

```
class CustomView(LoggingMixin, APIView):
        
        def post(self, request, *args, **kwargs):
            # do something here.
```
I do not do anything overriding since I want to use the default.
But the thing here is when i tried to upload its causes the bug.

Method 1:
- Removing LoggingMixin
It works. Though why do I do that?

Method 2:
- Upon reading the error I stumbled with. 
During handling of the above exception (Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.), another exception occurred:...
- DATA_UPLOAD_MAX_MEMORY_SIZE pertains to settings.py which by default is 2.5mb 2.6m-ish something on docs.

### solution: change the size. e.g DATA_UPLOAD_MAX_MEMORY_SIZE = 4mil-ish or None (is it good)?

> Though its weird why in APIView itself does not trigger that error (w/o LoggingMixin) ?

btw I had nginx setup which : 

```
server:{
    client_max_body_size 10M;
}
```
or maybe this one /\ is the answer to my confusion.

### Just an Update:
nginx had nothing to do it throws another error

### solution: change the size DATA_ larger than the nginx and let nginx handle the error.

so if you stumble with the same issue as mine hopefully this help . And much apprecidated if someone can answer that kind of behavior
